export const mockExpenseData = [
  {
    id: "1",
    amount: 15.0,
    type: "parking",
    date: "2023-12-15",
    description: "Downtown parking garage",
  },
  {
    id: "2",
    amount: 120.0,
    type: "violation",
    date: "2023-12-10",
    description: "Speeding ticket",
  },
  {
    id: "3",
    amount: 45.5,
    type: "gasoline",
    date: "2023-12-05",
    description: "Shell gas station - full tank",
  },
  {
    id: "4",
    amount: 10.0,
    type: "parking",
    date: "2023-12-01",
    description: "Mall parking",
  },
  {
    id: "5",
    amount: 42.75,
    type: "gasoline",
    date: "2023-11-25",
    description: "Chevron gas station",
  },
  {
    id: "6",
    amount: 250.0,
    type: "maintenance",
    date: "2023-11-20",
    description: "Oil change and tire rotation",
  },
  {
    id: "7",
    amount: 8.0,
    type: "parking",
    date: "2023-11-15",
    description: "Airport short-term parking",
  },
  {
    id: "8",
    amount: 40.25,
    type: "gasoline",
    date: "2023-11-10",
    description: "Exxon gas station",
  },
  {
    id: "9",
    amount: 75.0,
    type: "violation",
    date: "2023-11-05",
    description: "Parking ticket - expired meter",
  },
  {
    id: "10",
    amount: 350.0,
    type: "maintenance",
    date: "2023-11-01",
    description: "Brake pad replacement",
  },
]
